server:
  port: 8088

spring:
  application:
    name: alpha
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draft?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: "null"
  global-config:
    db-config:
      update-strategy: IGNORED
  mapper-locations: classpath:/mapper/**.xml




